name: logger
description: Simple logging library for Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  intl: any
  meta: ^1.16.0
  stack_trace: ^1.12.1
